# Generated by Django 4.0.5 on 2022-06-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='user_article_id',
            new_name='user_article',
        ),
    ]
