# Generated by Django 4.0.5 on 2022-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0002_rename_user_article_id_cashflow_user_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
