# Generated by Django 4.0.5 on 2022-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0003_alter_cashflow_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='fin_month',
            field=models.DateField(verbose_name='Місяць'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='sum',
            field=models.FloatField(verbose_name='Сума'),
        ),
    ]
