# Generated by Django 4.0.5 on 2022-06-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0004_alter_article_title_alter_cashflow_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='user_article',
            new_name='article',
        ),
    ]
