# Generated by Django 4.0.5 on 2022-06-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0005_rename_user_article_cashflow_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
